print("Sekos tukša rinda") 
print()
print("Visi ", end="")
print("vārdi ", end="")
print("vienā ", end="")
print("rindā ")
print("Visi ", end="")
print("vārdi ", end="")
print("vienā ", end="")
print("rindā ")
print("No ", end="")
print("zvaigznītēm ", end="")
print( "* ", end="")
print("veidots ", end="")
print("trijstūris ")
print("  *")
print(" *", "*")
print("*****")