#for cikls
#for i in range (1,10):
 #print(str(i)*i)

#vecums=int(input("Ievadiet skaitli: "))
#for i in range (1,10):
    #if vecums <=2:
       #print(vecums*10.5,"gadi")
      # break
   # elif vecums > 2:
       #print(vecums*4,"gadi")
      # break
   # elif i <= 0:
     #  ("Nevar! ")

#for i in range (1,21):
  # print(i,".autobusa pietura")


for z in range (1,14):
        print("*",* "*" +"*")

rinda = 7
for i in range(0,rinda):
    for j in range(0,i+1):
        print("*",end=" ")
    print("\r")
for i in range(rinda, 0, -1):
    for j in range(0,i-1):
        print("*",end=" ")
        print("\r")